version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 6
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
    groups:
      security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
          - major
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor
      major:
        applies-to: version-updates
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 6
    groups:
      security:
        applies-to: security-updates
        update-types:
          - patch
          - minor
          - major
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - patch
          - minor
      major:
        applies-to: version-updates
        update-types:
          - major
